package tanstackgen

import (
	_ "embed"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"
	"text/template"

	"github.com/blazy-vn/goctl/api/spec"
	apiutil "github.com/blazy-vn/goctl/api/util"
	"github.com/blazy-vn/goctl/internal/version"
	"github.com/blazy-vn/goctl/util"
	"github.com/blazy-vn/goctl/util/pathx"
)

//go:embed components.tpl
var componentsTemplate string

const sharedTypesFile = "shared-types"

func genTypes(dir string, api *spec.ApiSpec) error {
	if len(api.Types) == 0 {
		return nil
	}

	groupedTypes, sharedTypeNames := groupTypesByUsage(api)
	var moduleNames []string

	for module, types := range groupedTypes {
		if len(types) == 0 {
			continue
		}

		sort.Slice(types, func(i, j int) bool {
			return types[i].Name() < types[j].Name()
		})

		inShared := module == sharedTypesFile
		val, needsShared, err := BuildTypes(types, sharedTypeNames, inShared)
		if err != nil {
			return err
		}

		filename := path.Join(dir, module+".ts")
		if err := pathx.RemoveIfExist(filename); err != nil {
			return err
		}

		fp, created, err := apiutil.MaybeCreateFile(dir, ".", module+".ts")
		if err != nil {
			return err
		}
		if !created {
			continue
		}
		defer fp.Close()

		t := template.Must(template.New("componentsTemplate").Parse(componentsTemplate))
		data := map[string]string{
			"componentTypes": strings.TrimSpace(val),
			"version":        version.BuildVersion,
		}
		if needsShared && !inShared {
			data["sharedImport"] = `import * as shared from "./shared-types"`
		}
		if err := t.Execute(fp, data); err != nil {
			return err
		}

		moduleNames = append(moduleNames, module)
	}

	sort.Strings(moduleNames)
	return writeTypesBarrel(dir, api, moduleNames)
}

func writeTypesBarrel(dir string, api *spec.ApiSpec, modules []string) error {
	if len(modules) == 0 {
		return nil
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by goctl. DO NOT EDIT.\n")
	for _, module := range modules {
		builder.WriteString(fmt.Sprintf(`export * from "./%s"`, module))
		builder.WriteString("\n")
	}

	filename := path.Join(dir, typesFileName(api))
	if err := pathx.RemoveIfExist(filename); err != nil {
		return err
	}

	return os.WriteFile(filename, []byte(strings.TrimSpace(builder.String())+"\n"), 0o644)
}

func groupTypesByUsage(api *spec.ApiSpec) (map[string][]spec.Type, map[string]struct{}) {
	typeUsage := make(map[string]map[string]struct{})
	typeDefs := make(map[string]spec.DefineStruct)
	for _, tp := range api.Types {
		if ds, ok := tp.(spec.DefineStruct); ok {
			typeDefs[util.Title(ds.Name())] = ds
		}
	}

	for _, group := range api.Service.Groups {
		groupBase := groupFileBase(api, group)
		for _, route := range group.Routes {
			markTypeUsage(typeUsage, groupBase, route.RequestType, typeDefs, make(map[string]struct{}))
			markTypeUsage(typeUsage, groupBase, route.ResponseType, typeDefs, make(map[string]struct{}))
		}
	}

	grouped := make(map[string][]spec.Type)
	sharedNames := make(map[string]struct{})
	for _, tp := range api.Types {
		typeName := util.Title(tp.Name())
		groupSet := typeUsage[typeName]
		switch len(groupSet) {
		case 0:
			grouped[sharedTypesFile] = append(grouped[sharedTypesFile], tp)
			sharedNames[typeName] = struct{}{}
		case 1:
			for groupBase := range groupSet {
				grouped[groupBase+"-types"] = append(grouped[groupBase+"-types"], tp)
			}
		default:
			grouped[sharedTypesFile] = append(grouped[sharedTypesFile], tp)
			sharedNames[typeName] = struct{}{}
		}
	}

	return grouped, sharedNames
}

func markTypeUsage(usage map[string]map[string]struct{}, groupBase string, tp spec.Type, typeDefs map[string]spec.DefineStruct, seen map[string]struct{}) {
	if tp == nil || len(groupBase) == 0 {
		return
	}

	switch v := tp.(type) {
	case spec.PointerType:
		markTypeUsage(usage, groupBase, v.Type, typeDefs, seen)
	case spec.ArrayType:
		markTypeUsage(usage, groupBase, v.Value, typeDefs, seen)
	case spec.DefineStruct:
		typeName := util.Title(v.Name())
		if _, ok := seen[typeName]; ok {
			return
		}
		seen[typeName] = struct{}{}
		if usage[typeName] == nil {
			usage[typeName] = make(map[string]struct{})
		}
		usage[typeName][groupBase] = struct{}{}

		// Recurse into members
		ds, ok := typeDefs[typeName]
		if !ok {
			ds = v
		}
		for _, member := range ds.Members {
			if member.IsInline {
				markTypeUsage(usage, groupBase, member.Type, typeDefs, seen)
				continue
			}
			markTypeUsage(usage, groupBase, member.Type, typeDefs, seen)
		}
	}
}
