package tsgen

import (
	_ "embed"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"
	"text/template"

	"github.com/blazy-vn/goctl/api/spec"
	apiutil "github.com/blazy-vn/goctl/api/util"
	"github.com/blazy-vn/goctl/internal/version"
	"github.com/blazy-vn/goctl/util"
	"github.com/blazy-vn/goctl/util/pathx"
)

//go:embed components.tpl
var componentsTemplate string

const sharedComponentsFile = "shared-components"

// BuildTypes generates the typescript code for the types.
func BuildTypes(types []spec.Type) (string, error) {
	var builder strings.Builder
	first := true
	for _, tp := range types {
		if first {
			first = false
		} else {
			builder.WriteString("\n")
		}
		if err := writeType(&builder, tp); err != nil {
			return "", apiutil.WrapErr(err, "Type "+tp.Name()+" generate error")
		}
	}

	return builder.String(), nil
}

func genComponents(dir string, api *spec.ApiSpec) error {
	if len(api.Types) == 0 {
		return nil
	}

	groupedTypes := groupComponentTypesByUsage(api)
	var moduleNames []string

	for module, types := range groupedTypes {
		if len(types) == 0 {
			continue
		}

		sort.Slice(types, func(i, j int) bool {
			return types[i].Name() < types[j].Name()
		})

		val, err := BuildTypes(types)
		if err != nil {
			return err
		}

		filename := path.Join(dir, module+".ts")
		if err := pathx.RemoveIfExist(filename); err != nil {
			return err
		}

		fp, created, err := apiutil.MaybeCreateFile(dir, ".", module+".ts")
		if err != nil {
			return err
		}
		if !created {
			continue
		}
		defer fp.Close()

		t := template.Must(template.New("componentsTemplate").Parse(componentsTemplate))
		if err := t.Execute(fp, map[string]string{
			"componentTypes": val,
			"version":        version.BuildVersion,
		}); err != nil {
			return err
		}

		moduleNames = append(moduleNames, module)
	}

	sort.Strings(moduleNames)
	return writeComponentsBarrel(dir, api, moduleNames)
}

func writeComponentsBarrel(dir string, api *spec.ApiSpec, modules []string) error {
	if len(modules) == 0 {
		return nil
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by goctl. DO NOT EDIT.\n")
	for _, module := range modules {
		builder.WriteString(fmt.Sprintf(`export * from "./%s"`, module))
		builder.WriteString("\n")
	}

	outputFile := apiutil.ComponentName(api) + ".ts"
	if err := pathx.RemoveIfExist(path.Join(dir, outputFile)); err != nil {
		return err
	}

	return os.WriteFile(path.Join(dir, outputFile), []byte(strings.TrimSpace(builder.String())+"\n"), 0o644)
}

func groupComponentTypesByUsage(api *spec.ApiSpec) map[string][]spec.Type {
	typeUsage := make(map[string]map[string]struct{})

	for _, group := range api.Service.Groups {
		groupBase := groupFileBase(api, group)
		for _, route := range group.Routes {
			addTypeUsage(typeUsage, getComponentTypeName(route.RequestType), groupBase)
			addTypeUsage(typeUsage, getComponentTypeName(route.ResponseType), groupBase)
		}
	}

	grouped := make(map[string][]spec.Type)
	for _, tp := range api.Types {
		typeName := util.Title(tp.Name())
		groupSet := typeUsage[typeName]
		switch len(groupSet) {
		case 0:
			grouped[sharedComponentsFile] = append(grouped[sharedComponentsFile], tp)
		case 1:
			for groupBase := range groupSet {
				grouped[groupBase+"-components"] = append(grouped[groupBase+"-components"], tp)
			}
		default:
			grouped[sharedComponentsFile] = append(grouped[sharedComponentsFile], tp)
		}
	}

	return grouped
}

func addTypeUsage(usage map[string]map[string]struct{}, typeName, groupBase string) {
	if len(typeName) == 0 || len(groupBase) == 0 {
		return
	}
	if usage[typeName] == nil {
		usage[typeName] = make(map[string]struct{})
	}
	usage[typeName][groupBase] = struct{}{}
}

func getComponentTypeName(tp spec.Type) string {
	if tp == nil {
		return ""
	}

	switch v := tp.(type) {
	case spec.DefineStruct:
		return util.Title(tp.Name())
	case spec.PointerType:
		return getComponentTypeName(v.Type)
	case spec.ArrayType:
		return getComponentTypeName(v.Value)
	default:
		return ""
	}
}
